[package]
name = "scrust"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
colored = "2.0.0"