name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-scrust:
    name: Build Scrust for ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: "x86_64-unknown-linux-gnu"
            os: ubuntu-latest
          - target: "x86_64-pc-windows-msvc"
            os: windows-latest
          - target: "x86_64-apple-darwin"
            os: macos-latest
    runs-on: ${{ matrix.os }}
    env:
      ARTIFACT_NAME: ${{ matrix.os == 'windows-latest' && 'disco-core.exe' || 'disco-core' }}
    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - name: Build for ${{ matrix.target }}
      run: cargo build --release --target ${{ matrix.target }}
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: scrust-${{ matrix.target }}
        path: /target/${{ matrix.target }}/release/${{ env.ARTIFACT_NAME }}
      
